class Books {
  String name, author, price, image, description;
  bool isPopular;

  Books(
      {required this.name,
      required this.author,
      required this.price,
      required this.image,
      this.isPopular = false,
      required this.description});
}

var booksList = [
  Books(
    name: "Pattern Maker",
    author: "Kerry Johnston",
    image: "assets/images/4.png",
    price: "11,8",
    isPopular: true,
    description:
        "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text.\n\nAll the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.",
  ),
  Books(
      name: "Sebuah Seni Untuk Bersikap Bodo Amat",
      author: "Mark Manson",
      image: "assets/images/7.jpeg",
      price: "8,2",
      isPopular: true,
      description:
          'Buku ini menceritakan tentang Harles Bokowski seorang pecandu alkohol senang bermain perempuan,pejudi kronis,kasar,kikir,dan tukang utang.Ia bercita-cita menjadi seorang penulis.karya Bukowski selalu di tolak oleh hampir setiap majalah,tetapi hal tersebut tidak membuat nya menyerah ia tetap menulis dan membuat puisi.\n\nTumpukan kertas-kertas semakin menggunung yang berisi penolakan,cacian,tentang karyanya.Tiga puluh tahun berjalan tanpa arti hampir seluruh waktunya dalam bayang-bayang alkohol,narkoba,judi,dan pelacuran,hingga pada usia 50 tahun seorang editor di sebuah penerbitan menaruh minat yang aneh terhadap dirinya.\n\nKonten ini telah tayang di Kompasiana.com dengan judul "Resensi Buku "Sebuah Seni untuk Bersikap Bodo Amat\n\nSampai akhirnya ia sukses dengan judul novel pertama post office "Didedikasikan untuk tak seorang pun". Popularitasnya melampaui harapan setiap orang.\n\nWalaupun ia sudah sukses ia tetap menjadi dirinya sendiri minum alkohol,menggunakan narkoba,main perempuan dan lain sebagainya. Sukses tidak mengubah hidupnya menjadi pribadi yang lebih baik\n\nBaginya cuek dan masa bodoh adalah cara sederhana untuk mengrahkan kembali ekspetasi hidup dalam memilih apa yang penting karna pada intinya hidup hanyalah rentetan masalah yang tidak ada ujungnya. Novel ini adalah kisah nyata dari hidupnya yang selalu di terpa oleh kencangnya badai dan karena itulah ia menjadi semakin kuat dalam meraih cita-cita.'),
  Books(
      name: "Kata",
      author: "Nadhifa Allya Tsana",
      image: "assets/images/11.jpg",
      price: "7,5",
      isPopular: true,
      description:
          'Perempuan kuat bernama Binta Dineschara Prandipta, Masalah hidup selalu datang menghampiri Binta . Ketika usia ia 5 tahun, ayah nya meninggalkan Binta dan ibunya. Sehingga ibunya mengidap penyakit Skizofrenia, yaitu penyakit kejiwaan yang membuat si penderita tidak bisa membedakan mana yang nyata dan mana yang ada didalam pikirannya. Selama 15 tahun berlalu, ibu Binta hanya diam dan mengamuk ketika perasaannya sedang tidak baik. Binta adalah seorang yang sangat sulit untuk diajak bergaul, ya karna ia berfikir ia lebih baik mengurus ibunya dirumah daripada bergaul bersama teman-temannya. Ia hanya memiliki satu teman, Cahyo. Bahkan Cahyo saja membutuhkan waktu yang sangat lama agar ia bisa menjadi sahabat Binta. Cahyo sudah tau sifat Binta, ia juga sudah akrab dengan Ibunya Binta dan ia sudah tau masalah hidup apa saja yang sedang dihadapi oleh Binta.\n\nBinta adalah mahasiswi dari jurusan Ilmu Komunikasi tetapi Binta sama sekali tidak menikmati masa kuliahnya dalam jurusan tersebut. Binta sering sekali dikeluarkan dari kelas oleh dosen bagi Binta itu adalah hal yang biasa, untung saja setiap Binta lagi merasa bosan  dan jenuh Cahyo selalu ada untuknya, Cahyo sangat sabar menghadapi Binta. Cahyo sudah sering menasihati Binta tetapi tetap saja Binta keras kepala.\n\nKehidupan Binta di kampus pun tak begitu menyenangkan, ia lebih senang menghabiskan waktunya dengan kesendirian yang ia buat. Sampai suatu ketika ada seorang Nugraha yang muncul mengusik kehidupannya, termasuk perasaan Binta.\n\nNug atau Nugraha digambarkan seseorang yang memiliki seribu kotak kesabaran terlebih dalam menghadapi Binta yang begitu cuek. Selama pendekatan dengan Binta, hanya ada penolakan dan juga usiran untuknya agar menyerah saja, itu yang  hanya Nug terima, namun karena itulah Nug masih bertahan dan terus saja memperjuangkan Binta, bahkan hampir saja Binta luluh dengan kegigihan Nug.'),
  Books(
      name: "Falling Into Place",
      author: "Amy Zhang",
      image: "assets/images/12.jpg",
      price: "9,8",
      isPopular: true,
      description:
          'Satu hari setelah mempelajari sederet rumusan hukum Newton, Liz mencoba mempraktikkan hal itu pada mobilnya. Mobil Mercedes Benz miliknya dipacu kencang-kencang, berlari ke luar batas jalan.\n\nDi balik dandanan dan gaya sosialitanya yang terkenal di seantero kelas, para teman mungkin mengira Liz tidak akan mengambil keputusan naas tersebut. Tapi, nyatanya, Liz bukan gadis seceria itu, di balik kesedihan, kesendiriannya, dan kebungkamannya, tidak ada lagi yang dapat ia katakan. Kepada Monica, ibunya, yang tak hentinya bekerja seperti kaum nomaden. Telepon Liz hanya dianggapnya sebagai angin lalu.\n\nLiz telah mengambil keputusan seutuhnya. Ia menentukan tanggal, teknik yang tepat, dan mengira seorang pun takkan pernah tahu rencananya, alih-alih, Liam Oliver sangat mengenal Mercedes milik Liz, gadis yang telah dicintainya diam-diam sedari dulu.\n\nAksi percobaan bunuh diri yang didasari perhitungan rumus khas Newton, bisa jadi hal itulah yang coba Amy Zhang ramu ke dalam novel debutnya. Ide yang brilian. Kalau seringnya, seseorang yang bunuh diri sudah kehabisan logika, teknik yang gunakan Liz Emerson sebagai sang tokoh utamanya, malah dibeberkan dengan sederet rumus berlogika. Cukup sederhana, hanya melibatkan rumus-rumus Hukum Newton yang kerap dipelajari di tingkat SMA, tapi memberikan hawa yang berbeda bagi pembaca.\n\nTema bunuh diri sendiri kini juga sudah marak menjadi tema-tema yang acapkali diangkat dalam novel ber-genre young adult. Membaca “Falling into Place” sesungguhnya mengingatkan saya pada novel Gayle Foreman, “If I Stay” dan “The Lovely Bones” karya Alice Sebold. Bercerita tentang tekad bunuh diri seorang Liz Emerson, lantas ceritanya tidak hanya berkelindan pada masalah Liz, seperti pada novel “By the Time You Read This, I’ll be Dead”, tapi bagaimana ceritanya bergulir menuju pihak-pihak lain yang kerap menghabiskan waktu bersama dengan Liz. Ibunya, Monica; sahabatnya, Kennie dan Julia; dan Liam Oliver.'),
  Books(
      name: "Konspirasi Alam Semesta",
      author: "Fiersa Besari",
      image: "assets/images/10.jpg",
      price: "5,5",
      isPopular: true,
      description:
          'Terlahir dari ayah seorang “ekstapol” membuat Juang harus siap menghadapi setiap celaan dan cemoohan dari orang lain, bahkan tetangganya\n\nJuang Astrajingga seorang yang cukup rupawan, walau kumal dengan brewok tipis menghiasi wajah dan alis tebal menaungi sepasang mata tajam lelaki itu pernah menjadi petualang yang lompat dari stau pelukan ke pelukan lain. Baginya, pelukan adalah pelukan, soal perasaan, lain cerita.\n\nBandung, september 2011 Juang sedang mencari sebuah buku yang dikategorikan langka. Lalu tak sengaja menabrak seorang perempuan, dan tak sengaja pula saat Juang mengembalikan buku-buku yang terjatuh, mereka saling bertatap untuk pertama kalinya, yang seolah membuat jagat raya Juang berhenti.\n\nKita tak peranh tahu apa yang direncanakan alam semsta, saat Juang hendak melak-sanakan tugasnya untuk mewawancarai anak dari sinden Shinta Aksara, seorang yang memiliki sura emas dan membanggakan bangsanya di mancanegara, namun seperti dilupakan oleh bangsanya juga. Ana Tidae anak dari seorang sinden terkenal dan orang yang pernah ditabrak Juang saat berada di toko buku saat itu.\n\nBerawal dari tabrakan semesta keduanya dan naik bianglala berdua, sampai berencana untuk mendaki bersama. Senja memang memang membawa kita kepada kegelapan, namun jika kita tahu cara bersyukur, banyak bintang dalam gelap yang menunggu untuk kita nikmati. Senja menjadi awal dari kisah mereka berdua.Tugas yang diemban sebagai seorang jurnalis membuatnya harus melakukan sebuah perjalanan yang sangat beresiko. Meninggalkan Ana yang baru saja merasa nyaman di-sampingnya.\n\nSeketika berpulang dari perjalanan panjangnya selama berbulan-bulan, alam kembali mengujinya dengan kabar ibunya yang masuk rumah sakit karena lambungnya yang kini kian bertambah parah. Lagi-lagi Juang harus bertahan dan kuat menerima kenyataan hidup yang sedang dialaminya.'),
  Books(
      name: "Senja dan Pagi",
      author: "Alffy Rev & Linka Angelia",
      image: "assets/images/6.jpg",
      price: "5,3",
      isPopular: true,
      description:
          'Novel ini diangkat dari kisah nyata penulis yaitu Alffy dan Linka. Novel ini menceritakan tentang perjalanan cinta mereka yang di awali dengan pertemuan  dua pribadi yang berbeda namun memiliki mimpi yang sama.\n\nAlffy merupakan seorang musik produser,sinematografer, sutradara yang berjiwa idiealis dan nasionalis. Ia selalu memiliki ide-ide gila yg ia tuangkan dalam setiap karya yang ia buat. Ia berhasil mencapai puncak kariernya pada saat ia mengisi acara penutupan Asian Games 2018. Ia berhasil dilirik oleh panita Asian Games dari video unggahannya di YouTube. Video yang ia buat dengan perjuangan dan usaha keras akhirnya membuahkan hasil. Video tersebut adalah video cover lagu resmi Asian Games 2018 yang ia susun apik dengan pengambilan gambar di atas Gunung Penanggungan.\n\nWalaupun ia telah berhasil mencapai puncak kariernya, ia tak mau berhenti untuk membuat sebuah karya-karya baru. Ia memikirkan project selanjutnya yang akan ia kerjakan. Ia mendapatkan saran dari salah satu team kerjanya untuk membuat lagu tentang cinta. Bermula dari project ini lah ia bertemu dengan Linka. Awalnya ia hanya mencoba mencari partner kerja, lalu ia menemukan sosok Linka dari explore Instagram dan mencoba berkenalan dengannya. Ada hal yang menarik dari Linka yang membuat Alffy merubah tujuan awalnya. Alffy tak ingin project nya kali ini hanya sekedar rekaan, ia ingin sesuatu yang asli bukan settingan. Ia ingin jika lagu ini tentang cinta maka cinta itu harus sungguhan, bukan sandiwara semata. Maka dari itu iya memutuskan untuk mencari tahu lebih tentang sosok Linka.\n\n'),
  Books(
      image: 'assets/images/1.png',
      name: 'The Color of You',
      author: 'J.Thompson',
      price: '10,5',
      description:
          'Pernah nggak ngrasain capek dan lelah dengan kehidupan yang kita jalani saat ini? Ada banyak orang yang merasa nggak tahu mau kemana, nggak tahu harus ngapain setelah mendapatkan hal-hal yang sudah mereka dapatkan. Bahkan jika pun ia seorang superstar, ada hal-hal yang kadang sulit untuk diterima oleh diri kita, bahwa ada dunia yang kita lupakan. Sesuatu yang membuat kita bertanya, dunia itu sebenarnya seperti apa sih? Apakah dunia kita saat ini adaah dunia yang sangat kita impikan, dengan rutinitas kehidupan yang sudah kita lakukan setiap hari?. Jujur, ada banyak pertanyaan yang kadang membuat aku bertanya, apakah dunia yang aku rasakan adalah dunia yang juga sangat aku impikan? Ataukah dunia yang aku geluti sekarang membuat banyak beban terasa di pundak?\n\nSaat membaca buku Honest World ini, aku diajak untuk masuk ke dunia si beruang lucu dan menggemaskan bernama Honest. Dunia Honest bukanlah dunia yang kita alami saat ini. Dunia yang sangat jauh berbeda dan membuat aku bertanya, apakah aku benar-benar sudah jujur pada diriku sendiri? Jawabannya, belum.\n\nBuku Honest World ini ditulis oleh Nathalia Tanojo (admin @dearhonest) dalam format bahasa Inggris. Bukunya tipis banget, sekitar 90 an halaman. Tapi ada ilustrasi lucu di dalamnya berupa dunia Honest, si beruang yang akan mengantarkan kita pada 4 kunci kehidupan. Setiap kunci akan membawa kita pada penjelajahan dunia yang menakjubkan. Nah, mari kita lihat Honest World!'),
  Books(
      image: 'assets/images/2.png',
      name: 'Sending Some Love',
      author: 'Oliver Lewis',
      price: '8,5',
      description:
          "Everything these days is understandably viewed through the lense of the pandemic--even these blog posts. I've only written three over the last year, but I'm pretty sure all of them started with some sort of cry for \"normalcy\" or a statement on how books can help us deal with everything that has had to change. And while yes, this Valentine's Day will be another unusual holiday in the books, I feel confident in saying that one thing has NOT changed: long distance relationships are a tale as old as time! Be it through letters, emails, texts, tweets, post-it notes or even time travel, love finds a way no matter how far apart we are.\n\nNow I know nothing will ever replace pure face to face time, but there is some comfort in knowing that we as humans have always found new and creative ways to connect with those we love without seeing them face to face. Like flowers on the doorstep...handcrafted letters... late night phone calls...texts with GIFs from a favorite TV show... treasure hunts...free chocolate! See, isn't that a bit better? Is your heart getting warmer?\n\nI guess what I'm saying is that we actually have a lot of creative ways to connect with loved ones despite the distance. And they can even be surprisingly fun and romantic! Don't believe me? Check out our list below. There are some new releases, some oldies-but-goodies, a few that have more bumps in the road than others, but ALL of them are stories of people connecting even though they’re apart from each other. Plus, all those raw emotions and honest conversations that can only be shared when there's no eye contact? They make the old adage \"Distance makes the heart grow fonder\" ring truer than ever when that distance is finally closed.\n\nSo hang in there folks. Maybe spread some contactless love of your own this weekend<3 Our distance will eventually close too, and I can't wait to see all of you when it does (in a totally platonic, we-love-our-customers way)."),
  Books(
      image: 'assets/images/3.png',
      name: 'Your\' a Miracle',
      author: 'Mike McHargue',
      price: '6,4',
      description:
          '“Holding brain science in one hand and rich emotional presence in the other, this book feels timely and necessary.”—Shauna Niequist, New York Times bestselling author of Present Over Perfect\n\nWhy is there such a gap between what you want to do and what you actually do? The host of Ask Science Mike explains why our desires and our real lives are so wildly different—and what you can do to close the gap.\n\nFor thousands of years, scientists, philosophers, and self-help gurus have wrestled with one of the basic conundrums of human life: Why do we do the things we do? Or, rather, why do we so often not do the things we want to do? As a podcast host whose voice goes out to millions each month, Mike McHargue gets countless emails from people seeking to understand their own misbehavior—why we binge on Netflix when we know taking a walk outside would be better for us, or why we argue politics on Facebook when our real friends live just down the street. Everyone wants to be a good person, but few of us, twenty years into the new millennium, have any idea how to do that.\n\nIn You’re a Miracle (and a Pain in the Ass), McHargue addresses these issues. We like to think we’re in control of our thoughts and decisions, he writes, but science has shown that a host of competing impulses, emotions, and environmental factors are at play in every action we undertake. Touching on his podcast listeners’ most pressing questions, from relationships and ethics to stress and mental health, and sharing some of the biggest triumphs and hardships from his own life, McHargue shows us how some of our qualities that seem most frustrating—including “negative” emotions like sadness, anger, and anxiety—are actually key to helping humans survive and thrive. In doing so, he invites us on a path of self-understanding and, ultimately, self-acceptance.\n\nYou’re a Miracle (and a Pain in the Ass) is a guided tour through the mystery of human consciousness, showing readers how to live more at peace with themselves in a complex world.'),
  Books(
      image: 'assets/images/5.png',
      name: 'Pa/percra/f',
      author: 'Mike Brown',
      price: '10,2',
      description:
          'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of \"de Finibus Bonorum et Malorum\" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, \"Lorem ipsum dolor sit amet..\", comes from a line in section 1.10.32.\n\nThe standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from \"de Finibus Bonorum et Malorum\" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.'),
  Books(
      image: 'assets/images/8.jpg',
      name: 'Pangeran Cilik: Le Petit Prince',
      author: 'Antoine De Saint E',
      price: '7,7',
      description:
          'Buku ini bekisah tentang seorang Pangeran Cilik yang mengelilingi planet-planet bersama seorang pemuda yang terdampar di gurun pasir karena kerusakan mesin pesawat yang ia tumpangi sendirian. Setiap penggal cerita disertai dengan ilustrasi yang unik. Dari ilustrasi dan sampulnya, novel ini seperti ditujukan untuk anak kecil sebagai bahan dongeng sebelum tidur. Tapi ternyata saya keliru, kisah novel ini adalah renungan bagi manusia utamanya yang mengaku dewasa.\n\nAntoine dalam pengantarnya mengatakan “Semua orang dewasa pernah menjadi anak-anak (sekalipun hanya sedikit yang ingat).” Agaknya alasan inilah yang menjadi sebab tertulisnya kisah epik nan reflektif ini.\n\nSaya mengatakan itu karena manusia dewasa terkadang lupa pada hal lain di luar urusannya dan menganggap itu tidak penting. Seperti ketika si pemuda memperbaiki mesin pesawatnya dan Pangeran Cilik bertanya banyak hal yang menurut si pemuda adalah hal remeh, si pemuda mengacuhkannya dengan berkata, “Aku sedang sibuk dengan hal-hal serius.” Pangeran Cilik yang tidak pernah melupakan pertanyaannya itu kesal dan menggerutu, “Kamu bicara seperti orang dewasa.”“Seperti orang dewasa,” sejatinya bukan orang dewasa. Ya, seperti itulah manusia menganggap dirinya sudah layak disebut dewasa dengan melakukan pekerjaan rumit menurut anak kecil. Padahal dewasa tidak sesederhana itu.\n\nItu masih macam manusia pertama. Perjalanan Le Petit Prince merupakan rangkuman dari sebagian kecil karakter manusia di muka bumi ini. Selanjutnya karakter seorang raja yang menguasai asteroid kecil, saking kecilnya sampai seluruh permukaan asteroid itu tertutup oleh jubah indahnya. Bukan karena jubahnya yang besar tapi memang karena daerah kekuasaannya yang begitu sempit. Ia merasa berkuasa hingga seluruh perintahnya harus dipatuhi, pun oleh rakyat pertamanya itu. Agar Pangeran Cilik tidak pergi, sang Raja mengangkatnya menjadi menteri meski andai tidak ada yang akan diadili ia boleh mengadili dirinya sendiri. Perintah ini membuat Pangeran Cilik menggerutu lagi, “Orang-orang dewasa amat ganjil.”'),
  Books(
      image: 'assets/images/9.jpg',
      name: 'Nonversation',
      author: 'Valerie Patkar',
      price: '5,9',
      description:
          'Ospek Frathur, Institute of Technology, mempertemukan Theala Radista Queensy dengan Gamaliel Audirga Danuandra. Pertemuan yang kurang baik, tapi membuat Dirga penasaran dengan Theala. Rasa penasarannya terus berlanjut sampai ia tak sengaja bertemu dengan Theala di Starbucks Cik Ditiro sedang menangis. Dari pertemuan itulah mereka semakin dekat dan saling nyaman.\n\nTheala menganggap kedekatan mereka berdua hanyalah sebatas pertemanan saja, karena menurutnya, tidak mungkin Dirga menyukai Theala. Dirga selalu cepat berganti pacar. Sifat playboynya itulah yang membuat Theala berpikir demikian. Sebaliknya, Dirga memiliki perasaan lebih pada Theala. Dia selalu jatuh cinta dengan segala hal dalam diri Theala. Namun, dia tidak pernah bisa mengungkapkan perasaannya itu.\n\nSuatu hari, karena sebuah proyek dari kampus, Theala harus bekerja sama dengan Detrian Bhadrika. Theala pernah menyukai Trian ketika sekolah dulu, dan sekarang pun masih menyukainya. Diawali dengan proyek kampus, Theala dan Trian menjadi dekat lalu akhirnya berpacaran.\n\nHubungan Theala dan Trian sebenarnya tak luput dari  campur tangan Dirga. Dirga tahu bahwa Trian adalah cinta pertama Theala. Hatinya sakit melihat mereka berdua dekat, tapi ia memilih untuk melihat Theala bahagia bersama Trian. Itu karena Dirga selalu mengutamakan kebahagiaan Theala di atas segalanya.\n\nSingkat cerita, hubungan Theala dan Trian merenggang karena hadirnya masa lalu Trian dan kenyataan bahwa Theala selalu mencari Dirga setiap memiliki masalah. Lalu, mereka berdua putus ketika ibunya Theala masuk ke rumah sakit. Di hari itu juga, hubungan Theala dan Dirga pun putus karena ketidakjujuran Dirga dengan perasaannya sendiri. Tak lama, ibu Theala meninggal. Theala memutuskan untuk melanjutkan hidup di luar negeri dengan meninggalkan segala luka.'),
  Books(
      image: 'assets/images/13.jpg',
      name: 'Daisy Manis',
      author: 'Henry James',
      price: '4,5',
      description:
          'Ia sepenuhnya menyadari bahwa di Jenewa lelaki muda tidak akan bebas berbicara kepada wanita muda yang belum kawin, kecuali dengan syarat syarat tertentu, di sini Vevey, keadan begini sangat menguntungkan- seorang gadis Amerika yang cantik datang Mendekat dan berdiri di depannya di sebuah taman. Tetapi gadis Amerika yang cantik ini hanya memandangnya sekilas saja ketika mendengar penjelasan Winterbourne\n\nApakah ia seorang gadis kebanyakan dari Negara Bagian New York- apakah semua gadis di sana seperti dia, gadis-gadis yang manis yang punya banyak teman lelaki? Atau apakah gadis ini seorang muda yang punya pamrih, lancang dan menuruti hawa nafsu saja? Winterbourne telah kehilangan nalurinya untuk mengetahui hal itu dan pikirannya pun tak bisa lagi menolongnya. Nona Daisy Miller nampaknya begitu murni. Beberapa orang pernah memberitahu kepadanya bahwa gadis-gadis Amerika masih murni, orang lain mengatakan sebaliknya. \n\nNovel ini mengambarkan secara singkat hubungan manusia dengan tingkatan sosial, bahwa sudah semestinya seorang pesuruh itu tidak boleh dekat dengan anggota keluarga yang memperkerjakannya, tidak boleh makan bersama dengan anggota keluarga yang memperkerjakannya dan seorang pesururuh tidak boleh merokok. Bukankah itu hal yang sangat menyimpang dari hak asasi manusia? Kebebesan berteman? Kebebasan melalukan apa yang di inginkan? Hal perbedaan tingkatan sosial di mata masyarakat itupun di kutip dalam novel Daisy Manis ini.\n\n “Oh ibunya sama saja! Mereka memperlakukan pesuruh itu sebagai sahabat karib- sebagai seorang yang terhormat. Aku bertanya-tanya, barangkali pesuruh itu juga makan bersama-sama mereka. Mungkin sekali mereka memang belum pernah bergaul dengan pria yang punya sopan santun, yang berpakaian rapid an bagus, yang Nampak bagai lelaki terhormat. Barangkali saja pesuruh itu sesuai benar dengan angan-angan si gadis tentang seorang pangeran. Ia duduk bersama mereka di petamanan, di waktu sore hari. Aku kira pesuruh itu juga merokok”.'),
  Books(
      image: 'assets/images/14.png',
      name: 'Catatan dari Bawah Tanah',
      author: 'Fyodor Dostoyevski',
      price: '6,3',
      description:
          'Novel ini aku dapat dari acara tukar kado  yang diadakan oleh kantorku dengan sistem undian pada hari Valentine 2017, sebenarnya bukan aku yang mendapat nomer undian untuk buku ini, namun atasanku (bukan atasan biasa) yang mempunyai buku ini sebagai kado untuk ditukar bersikeras agar aku yang bisa mendapatkannya, alhasil dia menukarkan nomer undian untuk kadonya dengan nomer undian yang aku dapat. Aku senang bukan kepalang. Sebelumnya aku gak pernah tau pengarangnya, namun penerjemahnya Asrul Sani seseorang yang punya nama besar dalam sastra Indonesia. Aku konfirmasi ketemanku dan juga Googling ternyata si penulis adalah seorang penulis yang terkenal. Dan ternyata setelah kubaca aku hampir menyerah untuk mengerti maksudnya, meskipun begitu cara menulisnya yang tanpa sistem dan batasan menginspirasi.\n\nAku adalah lelaki berumur dua puluh empat tahun, seorang Rusia yang telah bekerja pada Kantor N, Aku sangat perasa sekali, menurutku hidupku suram, Aku tidak punya teman dan tidak mau berteman. Aku benci pada pekerjaan kantorku juga pada wajahku meskipun begitu aku tetap mengusahakan agar mukaku terlihat luhur. Aku tanpa malu sedikitpun berani mengatakan bahwa Aku seorang pengecut dan seorang budak hal itu kulakukan karena Aku lebih terpelajar. Aku menyesal karena aku adalah seorang romantis yang galau. Pernah Aku tidak ingin berbicara dengan siapaun juga dan pernah juga Aku tidak hanya mau berbicara tetapi juga ingin bersahabat.\n\nAku merasa bosan dengan kegiatan membacaku yang selalu kulakukan sendiri, membaca memang membantuku, memberi kenikmatan namun itu juga membosankan, karena itu Aku pergi pada kejahatan bawah tanahku yang busuk dan gelap. Aku tidak bisa melupakan sebuah kejadian ketika pada suatu malam seorang perwira yang telah kuhalangi jalannya mendorongku tanpa peringatan dan penjelasan lalu lewat seperti tidak melihat Aku sama sekali.'),
  Books(
      image: 'assets/images/15.jpg',
      name: 'Antologi Rasa',
      author: 'Ika Natassa',
      price: '4,7',
      description:
          'Novel Antologi Rasa karya Ika Natassa merupakan sebuah novel yang diterbitkan oleh penerbit Gramedia Pustaka Utama. Novel ini bercerita tentang lika-liku perjalanan asmara Keara yang bekerja di sebuah bank ternama di Indonesia.\n\nKeara yang diceritakan merupakan lulusan universitas di Amerika ini mempunyai gaya hidup tingkat tinggi. Kebiasaan yang dilakukan adalah clubbing, belanja, dan makan di resto mahal. Hal tersebut tidak berbeda dengan Harris Risjad, teman sekantor Keara. Namun, perbedaan diantara keduanya adalah Harris tidak suka belanja. Pertemuan Harris dan Keara terjadi ketika mereka sama-sama diterima kerja di sebuah bank yang ada di daerah Jalan Sudirman, Jakarta. Pada saat itu, Harris yang notabene juga merupakan seorang playboy ini langsung jatuh hati kepada Keara. Tidak seperti kebanyakan perempuan lainnya, Keara memiliki keunikan tersendiri dari sudut pandang Harris. Selain itu, kedekatan keduanya juga berlandaskan kepada perilaku yang sama, yaitu suka minum wine. Hal tersebut pula yang menjadikan Harris dan Keara menjadi dekat. Kedekatan tersebut terjalin sangat erat hingga Harris selalu ada untuk Keara. Entah untuk mengusir rasa bosan atau penat di kantor maupun untuk menemani Keara yang hanya ingin bersenang-senang dan mengeluarkan sisi Keara yang sebenarnya tanpa harus berpura-pura.\n\nSayangnya, Keara malah menyukai Ruly, teman sekantor yang pernah bersama-sama ditempatkan di daerah terpencil. Berkat penempatan kerja di daerah terpencil tersebut, Keara, Harris, Ruly, dan Denise menjadi sahabat hingga mereka kembali ke kantor utama di Jakarta. Kehidupan Ruly yang jauh dari hingar bingar kemewahan, alim, dan selalu bersikap baik kepada semua orang tersebut yang membuat Keara jatuh hati. Keara mengetahui bahwa perbuatan dan sikapnya jauh dari baik. Oleh sebab itu, Keara ingin mendapatkan pasangan yang tidak seperti dirinya yang tidak baik. Hal tersebut juga dapat menjawab alasan Keara hanya menganggap Harris teman saja. Terlebih lagi setelah perbuatan Harris yang dilakukan kepada Keara di tengah kondisi tidak sadarkan diri di Singapura membuat Keara tidak mengganggap Harris temannya lagi.'),
];
